# Generated by Django 5.1.3 on 2024-12-07 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("youtube", "0004_song"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Song",
        ),
    ]
